# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monoctl < Formula
  desc "CLI for Monoskope. AuthN & AuthZ for Kubernetes multi-cluster, multi-cloud environments."
  homepage "https://github.com/finleap-connect/monoctl"
  version "0.1.6"
  license "Apache"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/HaniAlshikh/monoctl/releases/download/v0.1.6/monoctl-osx-arm64.tar.gz"
      sha256 "31c75b5b6c7c42405a74084a996317e97f7c479db180f51471268296008ca0d8"

      def install
        bin.install "monoctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/HaniAlshikh/monoctl/releases/download/v0.1.6/monoctl-osx-amd64.tar.gz"
      sha256 "f9a4218efebabe5e551a06aceb7848c5391aefc948ade9d061f679075dfa93f9"

      def install
        bin.install "monoctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HaniAlshikh/monoctl/releases/download/v0.1.6/monoctl-linux-arm64.tar.gz"
      sha256 "b75348d928ea78bddabc5efcf99840a89be3e8e48cee291a279fd122cb3584d8"

      def install
        bin.install "monoctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/HaniAlshikh/monoctl/releases/download/v0.1.6/monoctl-linux-amd64.tar.gz"
      sha256 "77a9bc577660f4893cafc05a85622181b3a1cd85c2e9d8c48017a525e0a3709c"

      def install
        bin.install "monoctl"
      end
    end
  end
end
